### ISSUE TITLE
openSbi steps not working

### ISSUE THREAD

**Issue by irfanwa** [chipsalliance/dromajo#10]
On a linux machine, I am able to complete the following steps:
**Get a trivial buildroot (~ 23 min)
Get the Linux kernel up and running (~ 3 min)**

However the following step and those after it are not working:
**openSBI (~ ? min)**

I think 
**1) the "opensbi.dromajo.tar.gz" tarball is unavailable 
and/or 
2) the following path is missing from the opensbi-0.5 repository.
opensbi-0.5/build/platform/dromajo/firmware/fw_payload.bin**

**Comment by et-tommythorn** [comment]
Indeed.  Jose needs to add it.  Reassigning.

**Comment by et-tommythorn** [comment]
Eh, isn't https://github.com/chipsalliance/dromajo/blob/master/run/opensbi.dromajo.tar.gz the file you are looking for?

**Comment by irfanwa** [comment]
yes I found it in the run directory. That was not clear to me  in the instructions. Perhaps the instructions could be clarified. Thanks
