### ISSUE TITLE
linux build is not working on Macs

### ISSUE THREAD

**Issue by irfanwa** [chipsalliance/dromajo#9]
I was trying the Dromajo setup on my Mac. I got the riscv baremetal stuff to work but the linux build is not working.

In particular I am trying this part:
Linux with buildroot
Get a trivial buildroot (~ 23 min) 

I get an error. See screenshot. I installed gcc on my Mac using "brew install gcc" but it didn't help.

<img width="1244" alt="Screen Shot 2019-12-10 at 8 15 28 PM" src="https://user-images.githubusercontent.com/57513859/70591539-580ef200-1b8b-11ea-8712-75572199b037.png">

**Comment by et-tommythorn** [comment]
As far as I can tell this isn't a Dromajo issue; you're trying to build one of the examples usages.  They are probably not supported on macOS.  You should file the issue with them.

**Comment by irfanwa** [comment]
thanks. Noted
